{% set name = "landau" %}
{% set version = "1.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}pkg/landaupkg-{{ version }}.tar.gz
  sha256: b84f74557595d001578bb193028d228ec9f2cb9fefba9a7b7814e06639e8c111

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3,<4
    - numpy >1,<3
    - pandas >=2.2,<3
    - scipy >=1.11.0,<2
    - shapely >1,<=2.0.7
    - seaborn >=0.12,<=0.13.2
    - scikit-learn >=1.2,<2

test:
  imports:
    - landau
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eisenforschung/landau
  summary: A library to calculate thermodynamic equilibria and plot phase diagrams in the (semi-)grand ensemble.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pmrv
